# Generated by Django 5.0.2 on 2025-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Waluta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Informacja o płatności',
                'verbose_name_plural': 'Informacje o płatnościach',
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('video_url', models.URLField(verbose_name='Link do YouTube')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('is_training', models.BooleanField(default=False, verbose_name='Film szkoleniowy')),
            ],
            options={
                'verbose_name': 'Film YouTube',
                'verbose_name_plural': 'Filmy YouTube',
                'ordering': ['-date_added'],
            },
        ),
    ]
