# Generated by Django 5.0.2 on 2025-05-18 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Film premium'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publikacji'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='thumbnail_url',
            field=models.URLField(default='https://via.placeholder.com/320x180.png?text=Miniatura', verbose_name='URL miniatury'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(default='brak', max_length=20, verbose_name='ID filmu'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_premium_access', models.BooleanField(default=False)),
                ('premium_access_until', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
